### ISSUE TITLE
Exception on SaveChanges: There is already an open DataReader associated with this Connection which must be closed first.

### ISSUE THREAD

**Issue by svekl** [SapientGuardian/SapientGuardian.EntityFrameworkCore.MySql#4]
Hi, I decided to try "SapientGuardian.EntityFrameworkCore.MySql", used "AspNet5MultipleProject" as an example. Added some classes, DbContext, Add-Migration and Update-Database worked like charm. But when I try to insert some data like that:

```
db.NewClasses.Add(new NewClass
                    {
                        Date = DateTime.Now,
                        SomeValue = "val"
                    });
db.SaveChanges();
```

I get an exception "There is already an open DataReader associated with this Connection which must be closed first."

Can you, please, give me some advice, how to find out, what am I doing wrong?

**Comment by SapientGuardian** [comment]
That should've been fixed by https://github.com/SapientGuardian/mysql-connector-net-netstandard/pull/27 which went out in 6.9.812, but it looks like the nuget package dependency still has a minimum of 6.9.811, which is probably what's been brought into your project. I'm going to force a rebuild to bring up the minimum to 6.9.812, which should take care of this.

**Comment by SapientGuardian** [comment]
Can you update to SapientGuardian.EntityFrameworkCore.MySql 7.1.1 and see if you still have the problem?

**Comment by svekl** [comment]
Wow, works fine now, thank you for help and great package!
